/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2012-06-14 14:11:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.net.*;
import a.*;

public final class rec_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html class=\"no-js\" lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"utf-8\">\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\n");
      out.write("\n");
      out.write("\t<title>Recommendations | Weboo</title>\n");
      out.write("\t<meta name=\"description\" content=\"\">\n");
      out.write("\t<meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width\">\n");
      out.write("\t<link href=\"http://twitter.github.com/bootstrap/assets/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>\n");
      out.write("    <style>\n");
      out.write("      body {\n");
      out.write("        padding-top: 60px;\n");
      out.write("        padding-bottom: 10px;\n");
      out.write("      }\n");
      out.write("\t</style>\n");
      out.write("\t<link href=\"http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"colorbox.css\" />\r\n");
      out.write("\t<script src=\"js/libs/modernizr-2.5.3.min.js\"></script>\r\n");
      out.write("</head>\n");

try{
	String accessToken=request.getParameter("accessToken");
	System.out.println(accessToken);
	String movie=Recommendations.movieRec(accessToken);
	PrintStream p=new PrintStream(new FileOutputStream("movie.json"));
	p.println(movie);p.flush();
	p.close();
	String music=Recommendations.musicRec(accessToken);
	System.out.println(music+" this is printing from webpage");
	PrintStream p1=new PrintStream(new FileOutputStream("music.json"));
	p1.println(music);
	p1.close();
}catch(Exception e){e.printStackTrace();}

      out.write("\n");
      out.write("<body style=\"background:url(https://lh6.googleusercontent.com/-obBgN3vk1qs/TlOaB41zkcI/AAAAAAAAFJs/a34UV_6PfLw/grids.gif)\">\n");
      out.write("<img id=\"loader\" src=\"img/fbloader.gif\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("\t\t<div class=\"hero-unit\">\n");
      out.write("\t\t<div id=\"home\">\t\n");
      out.write("\t\t\t<h1><center>Get Some Recommendations !!</center></h1><br /><br />\n");
      out.write("\t\t\t<h2><center>Movie</center></h2>\n");
      out.write("\t\t\t<p><center>\n");
      out.write("\t\t\t\t<a id=\"movie\" class=\"btn btn-primary btn-large\">Movie Recommendations</a>\n");
      out.write("\t\t\t</center></p><br />\n");
      out.write("\t\t\t<h2><center>Music</center></h2>\n");
      out.write("\t\t\t<p><center>\n");
      out.write("\t\t\t\t<a id=\"music\" class=\"btn btn-primary btn-large\">Music Recommendations</a>\n");
      out.write("\t\t\t</center></p>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js\"></script>\r\n");
      out.write("<script>window.jQuery || document.write('<script src=\"js/libs/jquery-1.7.2.min.js\"><\\/script>')</script>\r\n");
      out.write("\r\n");
      out.write("<!-- scripts concatenated and minified via ant build script-->\n");
      out.write("<script src=\"js/jquery.colorbox-min.js\"></script>\r\n");
      out.write("<script src=\"js/plugins.js\"></script>\r\n");
      out.write("<script src=\"js/script.js\"></script>\r\n");
      out.write("<!-- end scripts-->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tvar _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];\r\n");
      out.write("\t(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];\r\n");
      out.write("\tg.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';\r\n");
      out.write("\ts.parentNode.insertBefore(g,s)}(document,'script'));\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
